---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: configmap - validations
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: no files found in basePath should fail
    set:
      configMapsFromFolder:
        enabled: true
        basePath: ci/configMapsFolder
    asserts:
      - failedTemplate:
          errorMessage: "No usable files found in the folder ci/configMapsFolder"
